name: be_talent_test
description: "A new Flutter project."

# O seguinte impede que o pacote seja publicado acidentalmente no pub.dev.
# Remova esta linha se deseja publicar no pub.dev.
publish_to: 'none'

# Define a versão e o número de build da aplicação.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependências necessárias para o funcionamento do projeto.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adicionando fontes personalizadas corretamente.
  fonts:
    - family: HelveticaNeue-Regular
      fonts:
        - asset: assets/fonts/HelveticaNeue-Regular.ttf
        

  # Adicionando ativos da aplicação.
  assets:
    - assets/images/logo.png
